export const PERMISSIONS = {
    // Parking Permissions
    PARKING_VIEW: "PARKING_VIEW",
    PARKING_CREATE: "PARKING_CREATE",
    PARKING_UPDATE: "PARKING_UPDATE",
    PARKING_DELETE: "PARKING_DELETE",
    PARKING_APPROVE: "PARKING_APPROVE",

    // Booking Permissions
    BOOKING_VIEW: "BOOKING_VIEW",
    BOOKING_CREATE: "BOOKING_CREATE",
    BOOKING_UPDATE: "BOOKING_UPDATE",
    BOOKING_DELETE: "BOOKING_DELETE",
    BOOKING_CONFIRM: "BOOKING_CONFIRM",
    BOOKING_CANCEL: "BOOKING_CANCEL",

    // User Management
    USER_VIEW: "USER_VIEW",
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
    USER_DISABLE: "USER_DISABLE",
    USER_ENABLE: "USER_ENABLE",

    // Customer Management
    CUSTOMER_VIEW: "CUSTOMER_VIEW",
    CUSTOMER_CREATE: "CUSTOMER_CREATE",
    CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
    CUSTOMER_DELETE: "CUSTOMER_DELETE",

    // Vehicle Management
    VEHICLE_VIEW: "VEHICLE_VIEW",
    VEHICLE_CREATE: "VEHICLE_CREATE",
    VEHICLE_UPDATE: "VEHICLE_UPDATE",
    VEHICLE_DELETE: "VEHICLE_DELETE",

    // Wallet Management
    WALLET_VIEW: "WALLET_VIEW",
    WALLET_LIST: "WALLET_LIST",
    WALLET_DEPOSIT: "WALLET_DEPOSIT",
    WALLET_WITHDRAW: "WALLET_WITHDRAW",
    WALLET_TRANSACTION_HISTORY: "WALLET_TRANSACTION_HISTORY",

    // Rating & Review Management
    RATING_VIEW: "RATING_VIEW",
    RATING_LIST: "RATING_LIST",
    RATING_MODERATE: "RATING_MODERATE",
    RATING_DELETE: "RATING_DELETE",

    // Configuration Management
    CONFIGURATION_VIEW: "CONFIGURATION_VIEW",
    CONFIGURATION_CREATE: "CONFIGURATION_CREATE",
    CONFIGURATION_UPDATE: "CONFIGURATION_UPDATE",
    CONFIGURATION_DELETE: "CONFIGURATION_DELETE",

    // Dashboard & Analytics
    DASHBOARD_VIEW: "DASHBOARD_VIEW",
    DASHBOARD_TOTAL_BOOKINGS: "DASHBOARD_TOTAL_BOOKINGS",
    DASHBOARD_TOTAL_REVENUE: "DASHBOARD_TOTAL_REVENUE",
    DASHBOARD_DAILY_STATS: "DASHBOARD_DAILY_STATS",
    DASHBOARD_MONTHLY_STATS: "DASHBOARD_MONTHLY_STATS",
    DASHBOARD_YEARLY_STATS: "DASHBOARD_YEARLY_STATS",

    // Financial & Revenue
    REVENUE_VIEW: "REVENUE_VIEW",
    REVENUE_EXPORT: "REVENUE_EXPORT",

    // Settings & Security
    SETTINGS_VIEW: "SETTINGS_VIEW",
    SETTINGS_UPDATE: "SETTINGS_UPDATE",
    SETTINGS_RESET_PASSWORD: "SETTINGS_RESET_PASSWORD",
    SETTINGS_CHANGE_PASSWORD: "SETTINGS_CHANGE_PASSWORD",
};

export const PERMISSION_LABELS: Record<string, string> = {
    // Parking
    [PERMISSIONS.PARKING_VIEW]: "View Parkings",
    [PERMISSIONS.PARKING_CREATE]: "Create Parking",
    [PERMISSIONS.PARKING_UPDATE]: "Update Parking",
    [PERMISSIONS.PARKING_DELETE]: "Delete Parking",
    [PERMISSIONS.PARKING_APPROVE]: "Approve Parking",

    // Booking
    [PERMISSIONS.BOOKING_VIEW]: "View Bookings",
    [PERMISSIONS.BOOKING_CREATE]: "Create Bookings",
    [PERMISSIONS.BOOKING_UPDATE]: "Update/Manage Bookings",
    [PERMISSIONS.BOOKING_DELETE]: "Delete Bookings",
    [PERMISSIONS.BOOKING_CONFIRM]: "Confirm Bookings",
    [PERMISSIONS.BOOKING_CANCEL]: "Cancel Bookings",

    // User
    [PERMISSIONS.USER_VIEW]: "View Users",
    [PERMISSIONS.USER_CREATE]: "Create Users",
    [PERMISSIONS.USER_UPDATE]: "Update Users",
    [PERMISSIONS.USER_DELETE]: "Delete Users",
    [PERMISSIONS.USER_DISABLE]: "Disable Users",
    [PERMISSIONS.USER_ENABLE]: "Enable Users",

    // Customer
    [PERMISSIONS.CUSTOMER_VIEW]: "View Customers",
    [PERMISSIONS.CUSTOMER_CREATE]: "Create Customers",
    [PERMISSIONS.CUSTOMER_UPDATE]: "Update Customers",
    [PERMISSIONS.CUSTOMER_DELETE]: "Delete Customers",

    // Vehicle
    [PERMISSIONS.VEHICLE_VIEW]: "View Vehicles",
    [PERMISSIONS.VEHICLE_CREATE]: "Create Vehicles",
    [PERMISSIONS.VEHICLE_UPDATE]: "Update Vehicles",
    [PERMISSIONS.VEHICLE_DELETE]: "Delete Vehicles",

    // Wallet
    [PERMISSIONS.WALLET_VIEW]: "View Wallet Details",
    [PERMISSIONS.WALLET_LIST]: "List All Wallets",
    [PERMISSIONS.WALLET_DEPOSIT]: "Make Wallet Deposits",
    [PERMISSIONS.WALLET_WITHDRAW]: "Process Withdrawals",
    [PERMISSIONS.WALLET_TRANSACTION_HISTORY]: "View Transaction History",

    // Rating & Reviews
    [PERMISSIONS.RATING_VIEW]: "View Ratings & Reviews",
    [PERMISSIONS.RATING_LIST]: "List All Ratings",
    [PERMISSIONS.RATING_MODERATE]: "Moderate Reviews",
    [PERMISSIONS.RATING_DELETE]: "Delete Ratings/Reviews",

    // Configuration
    [PERMISSIONS.CONFIGURATION_VIEW]: "View Configurations",
    [PERMISSIONS.CONFIGURATION_CREATE]: "Create Configurations",
    [PERMISSIONS.CONFIGURATION_UPDATE]: "Update Configurations",
    [PERMISSIONS.CONFIGURATION_DELETE]: "Delete Configurations",

    // Dashboard & Analytics
    [PERMISSIONS.DASHBOARD_VIEW]: "View Dashboard",
    [PERMISSIONS.DASHBOARD_TOTAL_BOOKINGS]: "View Total Bookings Stats",
    [PERMISSIONS.DASHBOARD_TOTAL_REVENUE]: "View Total Revenue Stats",
    [PERMISSIONS.DASHBOARD_DAILY_STATS]: "View Daily Statistics",
    [PERMISSIONS.DASHBOARD_MONTHLY_STATS]: "View Monthly Statistics",
    [PERMISSIONS.DASHBOARD_YEARLY_STATS]: "View Yearly Statistics",

    // Financial
    [PERMISSIONS.REVENUE_VIEW]: "View Revenue/Financials",
    [PERMISSIONS.REVENUE_EXPORT]: "Export Revenue Reports",

    // Settings
    [PERMISSIONS.SETTINGS_VIEW]: "View Settings",
    [PERMISSIONS.SETTINGS_UPDATE]: "Update Settings",
    [PERMISSIONS.SETTINGS_RESET_PASSWORD]: "Reset User Passwords",
    [PERMISSIONS.SETTINGS_CHANGE_PASSWORD]: "Change Own Password",
};

// Categorized permissions for better UI organization
export const PERMISSION_CATEGORIES = {
    "Parking Management": [
        PERMISSIONS.PARKING_VIEW,
        PERMISSIONS.PARKING_CREATE,
        PERMISSIONS.PARKING_UPDATE,
        PERMISSIONS.PARKING_DELETE,
        PERMISSIONS.PARKING_APPROVE,
    ],
    "Booking Management": [
        PERMISSIONS.BOOKING_VIEW,
        PERMISSIONS.BOOKING_CREATE,
        PERMISSIONS.BOOKING_UPDATE,
        PERMISSIONS.BOOKING_DELETE,
        PERMISSIONS.BOOKING_CONFIRM,
        PERMISSIONS.BOOKING_CANCEL,
    ],
    "User Management": [
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_DELETE,
        PERMISSIONS.USER_DISABLE,
        PERMISSIONS.USER_ENABLE,
    ],
    "Customer Management": [
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_UPDATE,
        PERMISSIONS.CUSTOMER_DELETE,
    ],
    "Vehicle Management": [
        PERMISSIONS.VEHICLE_VIEW,
        PERMISSIONS.VEHICLE_CREATE,
        PERMISSIONS.VEHICLE_UPDATE,
        PERMISSIONS.VEHICLE_DELETE,
    ],
    "Wallet & Transactions": [
        PERMISSIONS.WALLET_VIEW,
        PERMISSIONS.WALLET_LIST,
        PERMISSIONS.WALLET_DEPOSIT,
        PERMISSIONS.WALLET_WITHDRAW,
        PERMISSIONS.WALLET_TRANSACTION_HISTORY,
    ],
    "Reviews & Ratings": [
        PERMISSIONS.RATING_VIEW,
        PERMISSIONS.RATING_LIST,
        PERMISSIONS.RATING_MODERATE,
        PERMISSIONS.RATING_DELETE,
    ],
    "Configuration Management": [
        PERMISSIONS.CONFIGURATION_VIEW,
        PERMISSIONS.CONFIGURATION_CREATE,
        PERMISSIONS.CONFIGURATION_UPDATE,
        PERMISSIONS.CONFIGURATION_DELETE,
    ],
    "Dashboard & Analytics": [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.DASHBOARD_TOTAL_BOOKINGS,
        PERMISSIONS.DASHBOARD_TOTAL_REVENUE,
        PERMISSIONS.DASHBOARD_DAILY_STATS,
        PERMISSIONS.DASHBOARD_MONTHLY_STATS,
        PERMISSIONS.DASHBOARD_YEARLY_STATS,
    ],
    "Financial Access": [
        PERMISSIONS.REVENUE_VIEW,
        PERMISSIONS.REVENUE_EXPORT,
    ],
    "System Settings & Security": [
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,
        PERMISSIONS.SETTINGS_RESET_PASSWORD,
        PERMISSIONS.SETTINGS_CHANGE_PASSWORD,
    ],
};

// Parking Dashboard specific permissions (for parking staff users)
export const PARKING_DASHBOARD_PERMISSIONS = {
    "Booking Operations": [
        PERMISSIONS.BOOKING_VIEW,
        PERMISSIONS.BOOKING_CREATE,
        PERMISSIONS.BOOKING_UPDATE,
        PERMISSIONS.BOOKING_CONFIRM,
        PERMISSIONS.BOOKING_CANCEL,
    ],
    "Customer & Vehicle": [
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_UPDATE,
        PERMISSIONS.VEHICLE_VIEW,
        PERMISSIONS.VEHICLE_CREATE,
        PERMISSIONS.VEHICLE_UPDATE,
    ],
    "Financial & Wallet": [
        PERMISSIONS.WALLET_VIEW,
        PERMISSIONS.WALLET_TRANSACTION_HISTORY,
        PERMISSIONS.REVENUE_VIEW,
        PERMISSIONS.DASHBOARD_TOTAL_REVENUE,
    ],
    "Dashboard & Reports": [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.DASHBOARD_TOTAL_BOOKINGS,
        PERMISSIONS.DASHBOARD_DAILY_STATS,
        PERMISSIONS.DASHBOARD_MONTHLY_STATS,
    ],
    "Reviews Management": [
        PERMISSIONS.RATING_VIEW,
        PERMISSIONS.RATING_LIST,
    ],
    "Staff Management": [
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_DISABLE,
        PERMISSIONS.USER_ENABLE,
    ],
    "Settings": [
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_CHANGE_PASSWORD,
    ],
};

// System/PossibleTech Dashboard permissions (full system access)
export const SYSTEM_DASHBOARD_PERMISSIONS = PERMISSION_CATEGORIES;

// Helper function to get permissions based on context
export function getPermissionsByContext(isParkingDashboard: boolean) {
    return isParkingDashboard ? PARKING_DASHBOARD_PERMISSIONS : SYSTEM_DASHBOARD_PERMISSIONS;
}

export const DEFAULT_PERMISSIONS_BY_ROLE: Record<string, string[]> = {
    "PARKING_SUPER_ADMIN": [
        // Parking (view only, no create/delete/approve)
        PERMISSIONS.PARKING_VIEW,
        PERMISSIONS.PARKING_UPDATE,

        // Booking (full access)
        PERMISSIONS.BOOKING_VIEW,
        PERMISSIONS.BOOKING_CREATE,
        PERMISSIONS.BOOKING_UPDATE,
        PERMISSIONS.BOOKING_DELETE,
        PERMISSIONS.BOOKING_CONFIRM,
        PERMISSIONS.BOOKING_CANCEL,

        // User (manage parking staff)
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_DISABLE,
        PERMISSIONS.USER_ENABLE,

        // Customer
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_UPDATE,

        // Vehicle
        PERMISSIONS.VEHICLE_VIEW,
        PERMISSIONS.VEHICLE_CREATE,
        PERMISSIONS.VEHICLE_UPDATE,

        // Wallet
        PERMISSIONS.WALLET_VIEW,
        PERMISSIONS.WALLET_TRANSACTION_HISTORY,
        PERMISSIONS.WALLET_DEPOSIT,
        PERMISSIONS.WALLET_WITHDRAW,

        // Ratings
        PERMISSIONS.RATING_VIEW,
        PERMISSIONS.RATING_LIST,
        PERMISSIONS.RATING_MODERATE,

        // Dashboard
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.DASHBOARD_TOTAL_BOOKINGS,
        PERMISSIONS.DASHBOARD_TOTAL_REVENUE,
        PERMISSIONS.DASHBOARD_DAILY_STATS,
        PERMISSIONS.DASHBOARD_MONTHLY_STATS,
        PERMISSIONS.DASHBOARD_YEARLY_STATS,

        // Revenue
        PERMISSIONS.REVENUE_VIEW,
        PERMISSIONS.REVENUE_EXPORT,

        // Settings
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_CHANGE_PASSWORD,
        PERMISSIONS.SETTINGS_RESET_PASSWORD,
    ],
    "PARKING_MANAGER": [
        // Parking (view only)
        PERMISSIONS.PARKING_VIEW,

        // Booking
        PERMISSIONS.BOOKING_VIEW,
        PERMISSIONS.BOOKING_CREATE,
        PERMISSIONS.BOOKING_UPDATE,
        PERMISSIONS.BOOKING_CONFIRM,
        PERMISSIONS.BOOKING_CANCEL,

        // User (view only)
        PERMISSIONS.USER_VIEW,

        // Customer
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_CREATE,

        // Vehicle
        PERMISSIONS.VEHICLE_VIEW,
        PERMISSIONS.VEHICLE_CREATE,

        // Wallet (view only)
        PERMISSIONS.WALLET_VIEW,
        PERMISSIONS.WALLET_TRANSACTION_HISTORY,

        // Ratings (view only)
        PERMISSIONS.RATING_VIEW,
        PERMISSIONS.RATING_LIST,

        // Dashboard
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.DASHBOARD_TOTAL_BOOKINGS,
        PERMISSIONS.DASHBOARD_TOTAL_REVENUE,
        PERMISSIONS.DASHBOARD_DAILY_STATS,

        // Revenue (view only)
        PERMISSIONS.REVENUE_VIEW,

        // Settings
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_CHANGE_PASSWORD,
    ],
    "SYSTEM_ADMIN": [
        ...Object.values(PERMISSIONS),
    ],
    "SYSTEM_SUPER_ADMIN": [
        // Full access to everything
        ...Object.values(PERMISSIONS),
    ],
};
